force-app/main/default/objects/Order/fields/Engine_Code__c.field-meta.xml
<CustomField>
    <fullName>Engine_Code__c</fullName>
    <label>Engine Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicate__c</fullName>
    <label>Is Duplicate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Kubota_Id__c.field-meta.xml
<CustomField>
    <fullName>Kubota_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/LANDTX__c.field-meta.xml
<CustomField>
    <fullName>LANDTX__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Main_product_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire__c/Welcome_Call_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Welcome Call Questionnaire</label>
    <nameField>
        <displayFormat>WCQ-{0000}</displayFormat>
        <label>Welcome Call Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Call_Questionnaire__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Multi Picklist</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire__c/fields/Answer_Value__c.field-meta.xml
<CustomField>
    <fullName>Answer_Value__c</fullName>
    <label>Answer Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;TH&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KH</fullName>
                <label>Cambodia</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Laos</label>
            </value>
            <value>
                <fullName>TH</fullName>
                <label>Thailand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire__c/fields/Questionnaire_Label__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Label__c</fullName>
    <label>Questionnaire Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/Welcome_Call_Questionnaire_Link__c.object-meta.xml
<CustomObject>
    <label>Welcome Call Questionnaire Link</label>
    <nameField>
        <displayFormat>WCQ-LINK-{0000}</displayFormat>
        <label>Welcome Call Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/fields/Answer_Value__c.field-meta.xml
<CustomField>
    <fullName>Answer_Value__c</fullName>
    <label>Answer Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/fields/Answer_Value_All__c.field-meta.xml
<CustomField>
    <fullName>Answer_Value_All__c</fullName>
    <label>Answer Value (All)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/fields/Key_for_Saving__c.field-meta.xml
<CustomField>
    <fullName>Key_for_Saving__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique Key for Upsert: Wellcome Call SF Id &amp; Welcome_Call_Questionnaire_Setup</inlineHelpText>
    <label>Key for Saving</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/fields/Welcome_Call__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Call__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Welcome Call</label>
    <referenceTo>WelcomeCall__c</referenceTo>
    <relationshipLabel>Welcome Call Questionnaire Link</relationshipLabel>
    <relationshipName>Welcome_Call_Questionnaire_Link</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Link__c/fields/Welcome_Call_Questionnaire_Setup__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Call_Questionnaire_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Welcome Call Questionnaire Setup</label>
    <referenceTo>Welcome_Call_Questionnaire_Setup__c</referenceTo>
    <relationshipLabel>Welcome Call Questionnaire Link</relationshipLabel>
    <relationshipName>Welcome_Call_Questionnaire_Link</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Setup__c/Welcome_Call_Questionnaire_Setup__c.object-meta.xml
<CustomObject>
    <label>Welcome Call Questionnaire Setup</label>
    <nameField>
        <displayFormat>WCQ-SETUP-{0000}</displayFormat>
        <label>Welcome Call Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Call_Questionnaire_Setup__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRACTOR</fullName>
                <label>TRACTOR (รถแทรกเตอร์)</label>
            </value>
            <value>
                <fullName>COMBINE HARVESTER</fullName>
                <label>COMBINE HARVESTER (รถเกี่ยวข้าว)</label>
            </value>
            <value>
                <fullName>RICE TRANSPLANTER</fullName>
                <label>RICE TRANSPLANTER (รถดำนา)</label>
            </value>
            <value>
                <fullName>MINI EXCAVATOR</fullName>
                <label>MINI EXCAVATOR (รถขุด)</label>
            </value>
            <value>
                <fullName>SUGARCANE HARVESTER</fullName>
                <label>SUGARCANE HARVESTER (รถตัดอ้อย)</label>
            </value>
            <value>
                <fullName>DRONE</fullName>
            </value>
            <value>
                <fullName>VEGETABLE PLANT</fullName>
            </value>
            <value>
                <fullName>VEGETABLE PLANTER</fullName>
            </value>
            <value>
                <fullName>COMBINE_HARVESTER_Resolve</fullName>
                <isActive>false</isActive>
                <label>COMBINE HARVESTER (Resolve)</label>
            </value>
            <value>
                <fullName>DRONE_Resolve</fullName>
                <isActive>false</isActive>
                <label>DRONE (Resolve)</label>
            </value>
            <value>
                <fullName>MINI_EXCAVATOR_Resolve</fullName>
                <isActive>false</isActive>
                <label>MINI EXCAVATOR (Resolve)</label>
            </value>
            <value>
                <fullName>RICE_TRANSPLANTER_Resolve</fullName>
                <isActive>false</isActive>
                <label>RICE TRANSPLANTER (Resolve)</label>
            </value>
            <value>
                <fullName>SUGARCANE_HARVESTER_Resolve</fullName>
                <isActive>false</isActive>
                <label>SUGARCANE HARVESTER (Resolve)</label>
            </value>
            <value>
                <fullName>TRACTOR_Resolve</fullName>
                <isActive>false</isActive>
                <label>TRACTOR (Resolve)</label>
            </value>
            <value>
                <fullName>VEGATABLE_PLANT_Resolve</fullName>
                <isActive>false</isActive>
                <label>VEGATABLE PLANT (Resolve)</label>
            </value>
            <value>
                <fullName>WelcomeCall_Oversea</fullName>
                <isActive>false</isActive>
                <label>WelcomeCall Oversea</label>
            </value>
            <value>
                <fullName>WelcomeCall_Oversea_Resolve</fullName>
                <isActive>false</isActive>
                <label>WelcomeCall Oversea (Resolve)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Setup__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>Text(Welcome_Call_Questionnaire__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Setup__c/fields/Questionnaire_Label__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Label__c</fullName>
    <formula>Welcome_Call_Questionnaire__r.Questionnaire_Label__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Questionnaire Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Questionnaire_Setup__c/fields/Welcome_Call_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Call_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Welcome Call Questionnaire</label>
    <referenceTo>Welcome_Call_Questionnaire__c</referenceTo>
    <relationshipLabel>Welcome Call Questionnaire Setup</relationshipLabel>
    <relationshipName>Welcome_Call_Questionnaire_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WelcomeCall__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>Daily_Sales_Kads_Order__r.LANDTX__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WelcomeCall__c/fields/Daily_Sales_Kads_Order__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Kads_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Sales (Kads)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Daily_Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Welcome Call</relationshipLabel>
    <relationshipName>Welcome_Call</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WelcomeCall__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Welcome Call (Product)</relationshipLabel>
    <relationshipName>Welcome_Call</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WelcomeCall__c/recordTypes/TRACTOR.recordType-meta.xml
<RecordType>
    <fullName>TRACTOR</fullName>
    <active>true</active>
    <label>TRACTOR (รถแทรกเตอร์)</label>
</RecordType>

force-app/main/default/classes/FormWelcomeCallQuestionTest.cls
@isTest
public class FormWelcomeCallQuestionTest {

  

    @isTest
    static void testQuestionWelcome() {
        // สร้าง WelcomeCall__c
        RecordType accRec = [SELECT Id, Name FROM RecordType WHERE Name = 'person account oversea'];
        RecordType wcRec = [SELECT Id, Name FROM RecordType WHERE Name = 'TRACTOR (รถแทรกเตอร์)'];
        
        Account acc = new Account();
        acc.RecordTypeId = accRec.Id;
        acc.LastName = 'Last Name';
        acc.Kubota_VIP__c = '1234';
        acc.Citizen_Id__c = '1234';
        acc.Live_Status__c = 'Alive';
        insert acc;
        
        Product2 prod = new Product2();
        prod.Name = 'Product Name';
        prod.Material_Number__c = 'KUBOTA-KIS';
        prod.Family = 'TRACTOR';
        insert prod;
        
        // First Daily_Sales_Kads__c record with LANDTX__c = 'TH'
        order dsTH = new order();
        dsTH.AccountId = acc.Id;
        dsTH.Engine_Code__c = '1234';
        dsTH.Kubota_Id__c = acc.Id;
        dsTH.Product__c = prod.Id;
        dsTH.Product_Type__c = 'TRACTOR';
        dsTH.IS_Duplicate__c = 'No';
        dsTH.Status = 'Draft';
        dsTH.EffectiveDate = Date.newInstance(2025, 8, 16);
        dsTH.LANDTX__c = 'TH';
        insert dsTH;
        
        // Second Daily_Sales_Kads__c record with LANDTX__c = 'KM'
        order dsKM = new order();
        dsKM.AccountId = acc.Id;
        dsKM.Engine_Code__c = '5678';
        dsKM.Kubota_Id__c = acc.Id;
        dsKM.Product__c = prod.Id;
        dsKM.Product_Type__c = 'TRACTOR';
        dsKM.IS_Duplicate__c = 'No';
        dsKM.LANDTX__c = 'KH';
        dsKM.Status = 'Draft';
        dsKM.EffectiveDate = Date.newInstance(2025, 8, 16);
        insert dsKM;
        
        WelcomeCall__c wc = new WelcomeCall__c();
        wc.RecordTypeId = wcRec.Id;
        wc.Daily_Sales_Kads_Order__c = dsKM.Id;
        wc.Car_Type__c = 'TRACTOR';        
        wc.Customer__c = acc.Id;
        wc.Product_Detail__c = prod.Id;
        insert wc;
        
        // สร้างคำถาม
        Welcome_Call_Questionnaire__c question = new Welcome_Call_Questionnaire__c(
        Questionnaire_Label__c = 'What is your name?',
        Answer_Type__c = 'Text',
        Answer_Value__c = '',
        Country__c = 'KH'
            );
        insert question;
        
        Welcome_Call_Questionnaire_Setup__c setup = new Welcome_Call_Questionnaire_Setup__c(
        Car_Type__c = 'TRACTOR',
        Welcome_Call_Questionnaire__c = question.Id,
        Section_Name__c = 'Personal Info',
        Sequence__c = 1,
        Is_Active__c = true
            );
        insert setup;
        
        // สร้างคำตอบเดิม
        
        Welcome_Call_Questionnaire_Link__c answer = new Welcome_Call_Questionnaire_Link__c(
            Welcome_Call__c = wc.Id,
        Key_for_Saving__c = wc.Id,
        Answer_Value_All__c = setup.Id + '::John Doe'
            );
        insert answer;
        
        Welcome_Call_Questionnaire_Link__c answerDate = new Welcome_Call_Questionnaire_Link__c(
            Welcome_Call__c = wc.Id,
        Key_for_Saving__c = wc.Id,
        Answer_Value_All__c = setup.Id + '::John Doe::John Doe::John Doe'
            );
        insert answerDate;
        WelcomeCall__c welcomeCall = [SELECT Id FROM WelcomeCall__c LIMIT 1];
        
        Test.startTest();
        List<FormWelcomeCallQuestion.QuestionWithAnswerWrapper> result =
            FormWelcomeCallQuestion.QuestionWelcome(welcomeCall.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result);
    }

    @isTest
    static void testSaveAnswers() {
        RecordType accRec = [SELECT Id FROM RecordType WHERE Name = 'person account oversea' LIMIT 1];
        RecordType wcRec = [SELECT Id FROM RecordType WHERE Name = 'TRACTOR (รถแทรกเตอร์)' LIMIT 1];

        Account acc = new Account(
            RecordTypeId = accRec.Id,
            LastName = 'Last Name',
            Kubota_VIP__c = '1234',
            Citizen_Id__c = '1234',
            Live_Status__c = 'Alive'
        );
        insert acc;

        Product2 prod = new Product2(
            Name = 'Product Name',
            Material_Number__c = 'KUBOTA-KIS',
            Family = 'TRACTOR'
        );
        insert prod;

        order dsKM = new order(
            AccountId = acc.Id,
            Engine_Code__c = '5678',
            Kubota_Id__c = acc.Id,
            Product__c = prod.Id,
            Product_Type__c = 'TRACTOR',
            IS_Duplicate__c = 'No',
            LANDTX__c = 'KH',
            Status = 'Draft',
            EffectiveDate = Date.newInstance(2025, 8, 16)
        );
        insert dsKM;

        WelcomeCall__c wc = new WelcomeCall__c(
            RecordTypeId = wcRec.Id,
            Daily_Sales_Kads_Order__c = dsKM.Id,
            Car_Type__c = 'TRACTOR',
            Customer__c = acc.Id,
            Product_Detail__c = prod.Id
        );
        insert wc;

        Welcome_Call_Questionnaire__c question = new Welcome_Call_Questionnaire__c(
            Questionnaire_Label__c = 'What is your name?',
            Answer_Type__c = 'Text',
            Answer_Value__c = '',
            Country__c = 'KH'
        );
        insert question;

        Welcome_Call_Questionnaire_Setup__c setup = new Welcome_Call_Questionnaire_Setup__c(
            Car_Type__c = 'TRACTOR',
            Welcome_Call_Questionnaire__c = question.Id,
            Section_Name__c = 'Personal Info',
            Sequence__c = 1,
            Is_Active__c = true
        );
        insert setup;
        WelcomeCall__c welcomeCall = [SELECT Id FROM WelcomeCall__c LIMIT 1];

        // Mock answer data
        String mockAnswers =
            'a1lBK000000p965YAA:Chanathip;' +
            'a1lBK000000p966YAA:0988288714;' +
            'a1lBK000000p96HYAQ:คูโบต้าเก่านอก;' +
            'a1lBK000000p96JYAQ:1 ปี;';

        Map<String, String> answers = new Map<String, String>{
            'Answer_Value_All__c' => mockAnswers
        };

        Test.startTest();
        FormWelcomeCallQuestion.saveAnswers(welcomeCall.Id, answers);
        Test.stopTest();

        List<Welcome_Call_Questionnaire_Link__c> savedAnswers = [
            SELECT Id, Answer_Value__c, Welcome_Call__c
            FROM Welcome_Call_Questionnaire_Link__c
            WHERE Welcome_Call__c = :welcomeCall.Id
        ];

    }
}