force-app/main/default/objects/Account/fields/Dealer_Email_2__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Email_2__c</fullName>
    <label>Dealer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Plant_Code_Under_SSC_Account__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code_Under_SSC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Code Under SSC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.Main_SSC__c</field>
            <operation>equals</operation>
            <valueField>$Source.Primary_Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Service_Center__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Account.Main_Branch__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Dealer_Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases Account</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendEmailToDealer.cls
/**
 * @description       : 
 * @author            : wara.wangchai
 * @group             : 
 * @last modified on  : 08-19-2025
 * @last modified by  : wara.wangchai
**/
public class SendEmailToDealer {
    @auraEnabled
    public static Integer sendEmailToDealer(String recordId){
        Integer num = 0;
        for(Case cc : [SELECT Id,CaseNumber,Plant_Code_Under_SSC_Account__c FROM Case WHERE Id =: recordId]){
            
            contact con=[Select Id from contact Where LastName = 'System' limit 1];
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();  
            mail.setTargetObjectId(con.Id);
            mail.setWhatId(cc.Id);
            mail.setTemplateId('00X2x000000cecHEAQ');             
            mail.setBccSender(true); 
            mail.setUseSignature(false);  
            mail.setSaveAsActivity(true); 
            mail.setWhatId(cc.Id);
            List<String> sendTo = new List<String>();
               
            for(Account orgDir : [Select Dealer_Email__c, Dealer_Email_2__c from Account WHERE Id = :cc.Plant_Code_Under_SSC_Account__c]){
                //sendTo.add(orgDir.Email__c);
                String emailList = orgDir.Dealer_Email_2__c == null? orgDir.Dealer_Email__c : orgDir.Dealer_Email_2__c;
                for (String email : emailList.split(';')){
                    sendTo.add(email);
                }
                
            } 
            num = sendTo.size();
            
            mail.setToAddresses(sendTo); 
            if(num > 0){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
            System.debug('Number: ' + num);
        }
        
        return num;
    }  
}